#pragma once

#include <array>
#include <cstddef>

namespace onrobot_gripper_msgs {

/// Names and stable positions of the optional detailed device diagnostics
/// exported by the hardware adapters.  The values are state interfaces so the
/// standard GripperStateBroadcaster can publish them without owning device I/O.
enum class DiagnosticInterface : std::size_t {
  StatusValid,
  RawStatus,
  Busy,
  GripDetected,
  SampleSequence,
  Age,
  CommandForce,
  CommandForceValid,
  MeasuredForce,
  MeasuredForceValid,
  ForceProvenance,
  MotorVoltage,
  MotorCurrent,
  Temperature,
  RealtimeLinearVelocity,
  RealtimeAngularVelocity,
  RealtimeForce,
  SupplyPower,
  MaximumForce,
  MaximumRealtimeForce,
  StatisticsValid,
  ConventionalGripOnTime,
  PowerCycles,
  ConventionalGripCycles,
  GripDetectedCount,
  RealtimeGripOnTime,
  ForcePercent,
  FingerAngle,
  Diameter,
  DiameterWithTipOffset,
  Voltage24V,
  MinimumExternalAperture,
  MaximumExternalAperture,
  MinimumInternalAperture,
  MaximumInternalAperture,
  CurrentExternalAperture,
  CurrentInternalAperture,
  FingertipOffset,
  BoostPowerLimit,
  NotCalibrated,
  LinearSensorError,
  ExternalWidth,
  InternalWidth,
  MinimumExternalWidth,
  MaximumExternalWidth,
  MinimumInternalWidth,
  MaximumInternalWidth,
  AdditionalResults,
  LinearMechanismPosition,
  RawMotorWidth,
  Voltage5V,
  LinearCount,
  MotorSpeed,
  AngleSensorCount,
  LinearErrorCount,
  RealtimeExternalWidth,
  RgFingertipOffset,
  RgDepthAcceleration,
  RgDepthSpeed,
  RgActualDepth,
  RgActualRelativeDepth,
  RgMechanismAngle,
  RgLegacyAngularVelocity,
  RgActualWidth,
  RgVoltage5V,
  RgSafety24V,
  RgPlug24V,
  RgWidthWithFingertip,
  RgErrorCode,
  ThreeFingerForceGripDetected,
  ThreeFingerCalibrationValid,
  ThreeFingerGripLost,
  ThreeFingerPosition,
  IdentityValid,
  ProductCode,
  FirmwareMajor,
  FirmwareMinor,
  FirmwareBuild,
  BoardRevisionsValid,
  ProductRevision,
  HardwareRevision,
  PcbRevision,
  FirmwareCrcValid,
  FirmwareCrc,
  FirmwareSourceValid,
  FirmwareGitWord0,
  FirmwareGitWord1,
  FirmwareGitWord2,
  FirmwareGitWord3,
  FirmwareGitWord4,
  Count,
};

inline constexpr std::size_t kDiagnosticInterfaceCount =
    static_cast<std::size_t>(DiagnosticInterface::Count);

inline constexpr std::array<const char *, kDiagnosticInterfaceCount>
    kDiagnosticInterfaceNames{
        "diagnostic_status_valid",
        "diagnostic_raw_status",
        "diagnostic_busy",
        "diagnostic_grip_detected",
        "diagnostic_sample_sequence",
        "diagnostic_age",
        "diagnostic_command_force",
        "diagnostic_command_force_valid",
        "diagnostic_measured_force",
        "diagnostic_measured_force_valid",
        "diagnostic_force_provenance",
        "diagnostic_motor_voltage",
        "diagnostic_motor_current",
        "diagnostic_temperature",
        "diagnostic_realtime_linear_velocity",
        "diagnostic_realtime_angular_velocity",
        "diagnostic_realtime_force",
        "diagnostic_supply_power",
        "diagnostic_maximum_force",
        "diagnostic_maximum_realtime_force",
        "diagnostic_statistics_valid",
        "diagnostic_conventional_grip_on_time",
        "diagnostic_power_cycles",
        "diagnostic_conventional_grip_cycles",
        "diagnostic_grip_detected_count",
        "diagnostic_realtime_grip_on_time",
        "diagnostic_force_percent",
        "diagnostic_finger_angle_rad",
        "diagnostic_diameter_mm",
        "diagnostic_diameter_with_tip_offset_mm",
        "diagnostic_voltage_24v_v",
        "diagnostic_minimum_external_aperture_mm",
        "diagnostic_maximum_external_aperture_mm",
        "diagnostic_minimum_internal_aperture_mm",
        "diagnostic_maximum_internal_aperture_mm",
        "diagnostic_current_external_aperture_mm",
        "diagnostic_current_internal_aperture_mm",
        "diagnostic_fingertip_offset_mm",
        "diagnostic_boost_power_limit_w",
        "diagnostic_not_calibrated",
        "diagnostic_linear_sensor_error",
        "diagnostic_external_width_mm",
        "diagnostic_internal_width_mm",
        "diagnostic_minimum_external_width_mm",
        "diagnostic_maximum_external_width_mm",
        "diagnostic_minimum_internal_width_mm",
        "diagnostic_maximum_internal_width_mm",
        "diagnostic_additional_results_raw",
        "diagnostic_linear_mechanism_position_mm",
        "diagnostic_raw_motor_width_mm",
        "diagnostic_voltage_5v_v",
        "diagnostic_linear_count",
        "diagnostic_motor_speed_rpm",
        "diagnostic_angle_sensor_count",
        "diagnostic_linear_error_count",
        "diagnostic_realtime_external_width_mm",
        "diagnostic_rg_fingertip_offset_mm",
        "diagnostic_rg_depth_acceleration_mm_s2",
        "diagnostic_rg_depth_speed_mm_s",
        "diagnostic_rg_actual_depth_mm",
        "diagnostic_rg_actual_relative_depth_mm",
        "diagnostic_rg_mechanism_angle_rad",
        "diagnostic_rg_legacy_angular_velocity_rad_s",
        "diagnostic_rg_actual_width_mm",
        "diagnostic_rg_voltage_5v_v",
        "diagnostic_rg_safety_24v_v",
        "diagnostic_rg_plug_24v_v",
        "diagnostic_rg_width_with_fingertip_mm",
        "diagnostic_rg_error_code",
        "diagnostic_three_finger_force_grip_detected",
        "diagnostic_three_finger_calibration_valid",
        "diagnostic_three_finger_grip_lost",
        "diagnostic_three_finger_position",
        "diagnostic_identity_valid",
        "diagnostic_product_code",
        "diagnostic_firmware_major",
        "diagnostic_firmware_minor",
        "diagnostic_firmware_build",
        "diagnostic_board_revisions_valid",
        "diagnostic_product_revision",
        "diagnostic_hardware_revision",
        "diagnostic_pcb_revision",
        "diagnostic_firmware_crc_valid",
        "diagnostic_firmware_crc",
        "diagnostic_firmware_source_valid",
        "diagnostic_firmware_git_word_0",
        "diagnostic_firmware_git_word_1",
        "diagnostic_firmware_git_word_2",
        "diagnostic_firmware_git_word_3",
        "diagnostic_firmware_git_word_4"};

constexpr std::size_t diagnosticIndex(DiagnosticInterface i_interface) noexcept {
  return static_cast<std::size_t>(i_interface);
}

} // namespace onrobot_gripper_msgs
